# Generated by Django 3.1 on 2020-09-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200915_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='description',
        ),
    ]
