# Generated by Django 3.1 on 2020-09-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200916_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
