# Generated by Django 3.1 on 2020-08-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availabilty',
            field=models.CharField(choices=[('sold', 'verkocht'), ('available', 'beschikbaar')], default='available', max_length=50),
        ),
    ]
