# Generated by Django 3.1 on 2020-09-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_availabilty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availabilty',
            field=models.CharField(choices=[('sold', 'Sold'), ('available', 'Available')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='barbie', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
